export const FETCH_VISIT_DATA_BEGIN = 'FETCH_VISIT_DATA_BEGIN';
export const FETCH_VISIT_DATA_SUCCESS = 'FETCH_VISIT_DATA_SUCCESS';
export const FETCH_VISIT_DATA_FAILURE = 'FETCH_VISIT_DATA_FAILURE';
